In [10]:
'''
importing all the required libraries
'''
import requests
from bs4 import BeautifulSoup
import csv
import numpy as np
import pandas as pd

In [11]:
'''
get complete html content with thr help of beautifulSoup library
'''
source=requests.get("https://www.worldometers.info/coronavirus/").text
soup=BeautifulSoup(source,"html.parser")

In [12]:
'''
scrape for the required tag and write it to the csv file
'''
table=soup.find_all("table",{"id":"main_table_countries_today"})
tbody=table[0].find("tbody")
with open('Worldo_meter.csv', 'w', newline='',encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["SLno","Country","Total cases","New cases","Total deaths","New deaths","Total recovered","Active cases","Serious critical","Total cases/1M pop","Deaths/1M pop","Total Tests","Tests/1M pop","Population","Continent"])
    for country in tbody.find_all("tr"):
        write=[]
        for one in country.find_all("td"):
            write.append(one.text)
        writer.writerow(write)

In [13]:
'''
after writing into the csv file all the columns will be in object type.
but we need to convert it into interger for the visualization purpose.
'''
covid=pd.read_csv("Worldo_meter.csv")
covid.dropna(subset=["SLno"],how="any",inplace=True)
covid["Total cases"]=covid["Total cases"].str.replace(",","")
covid["Total cases"]=covid["Total cases"].astype("int64")

covid["Total deaths"]=covid["Total deaths"].str.replace(",","")
covid["Total deaths"]=covid["Total deaths"].str.replace(" ","")
covid.loc[covid["Total deaths"]=="","Total deaths"]=np.nan
covid["Total deaths"]=covid["Total deaths"].astype("Float32").astype("Int32")

covid["Active cases"]=covid["Active cases"].str.replace(",","")
covid["Active cases"]=covid["Active cases"].astype("Float32").astype("Int32")

covid["Population"]=covid["Population"].str.replace(",","")
covid["Population"]=covid["Population"].astype("int64")

covid["Total recovered"]=covid["Total recovered"].str.replace(",","")
covid["Total recovered"]=covid["Total recovered"].astype("Float32").astype("Int32")

In [14]:
'''
convert csv to excel sheet. 
one can do visualization in csv also. this line of code is optional
'''
covid.to_excel("Worldo_meter.xlsx",index=False)

In [15]:
'''
view some of the rows.
'''
covid.head()

,SLno,Country,Total cases,New cases,Total deaths,New deaths,Total recovered,Active cases,Serious critical,Total cases/1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population,Continent
8,1.0,USA,1706226,NaN,99805,NaN,464670,1141751,"17,114","5,158",302,"15,187,647","45,910",330811717,North America
9,2.0,Brazil,376669,NaN,23522,NaN,153833,199314,"8,318","1,773",111,"735,224","3,461",212409786,South America
10,3.0,Russia,362342,"+8,915",3807,174.0,131129,227406,"2,300","2,483",26,"9,160,590","62,775",145928485,Europe
11,4.0,Spain,282480,NaN,26837,NaN,196958,58685,854,"6,042",574,"3,556,567","76,071",46753049,Europe
12,5.0,UK,261184,NaN,36914,NaN,<NA>,<NA>,"1,559","3,849",544,"3,532,634","52,065",67851047,Europe